### ISSUE TITLE
Improve saved location management

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#15]
It would be great if I could rename saved location (ie ‘CEH’, ‘Garden’, ‘Mums house’, ‘pub’, etc) also would be great if I could favorite some locations so that they would always be at the top of that list.

**Comment by johnvanbreda** [comment]
Some comments on this area of the app:

- At first I didn't spot the Past tab so didn't realise there was a functionality for reusing locations.
- A common scenario is that I would visit a single site, walk around and collect records. In this scenario a single site name would have many different grid references. The Past tab lets me pick a grid ref and site name as a pair, but not just reuse the site name. I have to pick the site, then relocate using the GPS as a further step which is not very user friendly, and also impossible if I'm adding the site name after moving away from the original location of the record.
- A very common requirement would be to lock the location name field, or to recall the last entered location name so that you don't have to fiddle around whilst working on one site.

**Comment by kazlauskis** [comment]
Hi John, that is already in place, I just haven't made it very clear to everyone. For locking a location you can lock your specified _grid reference_ or a _map click_  **coordinates and a _location name_** you have provided.  **BUT** this does not apply to location acquired through _GPS_ as it will **just lock the location name**. Subsequent records would trigger _GPS_ call automatically, so in that case you would only have to enter species names and all the records will have fresh _GPS_ acquired coordinates plus the locked location name, date and other attributes you have locked. 

I hope that makes sense. Give it a try, add a new record with a location name and _GPS_ coords and lock it. You should find that the next record has an updated location (if you have moved far enough for gridref to be different).

**Comment by johnvanbreda** [comment]
That does indeed do exactly what I wanted. Therefore the only issue is making this behaviour more obvious as its not clear that the lock tool will do this unless you try.
