### ISSUE TITLE
Record 10-fig grid references

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#154]
From @japonicus regarding grid-mode location accurracy:

> The the vascular plant form has a field for GPS precision, so GPS'ed records could be sent as 10-fig gridrefs (1m precision points) with a radius. If an app user manually over-ruled the GPS-assigned ref then that would be sent instead (with no accuracy defined), but the default GPS response should always be to send 10-fig.

Links to: BiologicalRecordsCentre/BSBI-Card-and-PlantPortal#86

**Comment by davidgenney** [comment]
Hi Karolis. I have a related comment after trying the bryophyte recording mode (not in grid mode). The app helpfully shows a circle with size relative to precision, however the grid reference appears to be fixed at 100 resolution. I found it much easier to see the full grid reference resolution displayed along with the accuracy value.
I'm more concerned however that the OSGR value remains blured when uploaded and even when exported from the desktop site. While the precision is retained in the lat lon data field, this is less informative for non-GIS use.
Some great improvements though in terms of taxon specific fields.

**Comment by japonicus** [comment]
> Can the GPS facility of most mobile phones actually measure a GPS location to an accuracy of 1m?

not usually, but when dealing with centroids (which is what GPS readings fundamentally are) the most correct representation is as an absolute point and an error radius, rather than any type of square.

Regardless of precision, a square is always a poor representation of centroid, e.g. if the point lies in the corner of the square and the error margin is less than or equal to the square dimension then there's a 75% chance that the true position is outside the specified square.

Even with an optimal fit to a square (i.e. a point lying in the exact centre, with diameter matching the square) the square includes corner areas outside the centroid radius (21% of the square area).

It's trivial to coerce a centroid point with an error radius to fit a grid if that is what is need by the data user (e.g. to compile a gridded atlas) but that step represents a loss of accuracy. It's a transformation that should be done, if required, by the end user, not applied to the original raw record.

**Comment by kazlauskis** [comment]
Thanks for the comment David. I agree with @japonicus that lat/lon centroid + accuracy is best to submit from the app, but then there should be some helper functionality that would allow our users to see this represented as OSGR's if required. Unfortunately, any such helper functionality is opinionated in how it calculates the squares, so maybe we just need to provide more options to cover everyone's needs.

**Comment by davidgenney** [comment]
Thanks for the responses. I understand and agree with everything you say here about lat/lon point and radius being the most accurate spatial reference. 
My concern is that, as far as I'm aware, many recording schemes/national databases request OSGR coordinates. For those schemes that don't use iRecord I export my data and send them a spreadsheet. This means I'll loose detailed records in those databases because 10-m references will have been converted to 100-m references.  Not an issue in most cases, just specific fine-scale recording projects. Incidentally, I recently downloaded an app. that lets me calculate a much more accurate location by averaging the signal over multiple readings. For very important records I might use this and enter the location manually.
I'm also used to OSGR, which makes far more sense to me when looking up the reference or relative position within a grid. Again, I fully understand why lon/lat is better, but it will take some time before I learn to visualize this in the same way I visualize OSGR.
The new App. helpfully shows the error by varying the size of the circle about the point. I like this, but also value seeing the error as a value as per the previous version of the App. 
Hope that's a useful perspective.

**Comment by japonicus** [comment]
> I'm also used to OSGR, which makes far more sense to me when looking up the reference or relative position within a grid.

So am I. I think this is a major reason why, for recording in the British Isles, apps and websites should mostly avoid exposing lat/lng and instead use absolute precision (10-figure) grid-refs as the default format for presenting point locations (perhaps leaving an option to switch to lat/lng as a user-preference).

I don't have a good feel for the precision of a lat/lng co-ordinate. Working with values that [need to be expressed at 5 decimal places precision](https://en.wikipedia.org/wiki/Decimal_degrees#Precision) seems a nuisance and risks ambiguity if not expressed in a fixed decimal place format.

I don't mind how GPS geo-refs are represented internally (arguably lat/lng may be preferable) but _I only want to see_ 10-fig refs (with an error radius specified).

https://github.com/Indicia-Team/warehouse/issues/253 relates to this.

> I recently downloaded an app. that lets me calculate a much more accurate location by averaging the signal over multiple readings.

I'd be interested to know whether that makes much difference (perhaps by email, so as not to clutter this bug discussion) as I'd somewhat assumed that mobile devices would being doing that automatically.

**Comment by MNSmith** [comment]
I will repeat my comments about 10 figure grid refs.

1) Standard hand held GPS will not record to that degree of accuracy, so having the system "impose" a 1m accuracy on all recorded records is wrong.  If we cannot record to that degree of precision, we cannot provide an output that implies we can.

2) The NBN Atlas does not map at 10 figure / 1m resolution.  It converts all 10 fig grid refs submitted into 8 figure grid refs/ 10m accuracy dots on the map so having a 10 fig grid ref is pointless.  For most biological recording, a 10m "box" is a sufficiently detailed geo-location.

I agree that whatever way the system calculates geo-location, the default option on all inputs, outputs and verifcation grids within iRecord should be OS Grid Refs - lat/long, but please do not make the default a 10 figure grid.  There are some mapping programs that will not accept 10 fig refs, which makes for a lot of work to cut these down to 8 fig grid refs.

While we could go round in circles arguing thins point from a technical point of view, in terms of the end user (the NBN Atlas, National Schemes and Societies, LRCs etc), a 10 fig grid ref is not required.  Stick with 8 fig max.

**Comment by japonicus** [comment]
Hi Matt,
Very briefly, I don't think anyone's suggesting imposing a spurious 1m accuracy on records. The suggestion is that a 10-fig ref can be an appropriate way of designating the centre point of a centroid _which also has an error radius_. How subsequent data-consumers (including the iRecord website) handle that centroid is a separate issue.

I agree with you that it would be incorrect for such a record to be treated as a 1m square, so a system might either export the record as a centroid or fit it to a less precise grid-square based on the error radius, losing some accuracy in the process. Different users will need different  things.

If sent from iRecord to the NBN then a GPS'ed app record would be exported as a centroid not a grid-square. 

Incidentally, the NBN does accept 10-fig grid-refs (there's an example of such a record here: https://records.nbnatlas.org/occurrences/a6425b53-7c64-4722-ae3d-2b077566667d - though the likelihood is that that record shouldn't really be expressed so precisely). More generally though, the NBN is just one of a number of systems that receive records from iRecord, so the way it chooses to treat records is only tangentially relevant.

**Comment by kitenetter** [comment]
This issue has a lot of useful information in it, but I'm not seeing anything that requires further action now, so will close.
