### ISSUE TITLE
Record's user is both recorder and determiner?

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#17]
When the record goes to iRecord, does the system record the user as both recorder and determiner? I think it should.

**Comment by japonicus** [comment]
Isn't that just extra clutter on the record? Observations entered through the iRecord website leave the 'determiner' field blank by default. There the field is labelled, "If anyone helped with the identification please enter their name here" - which also seems to imply someone _other than the recorder_.

As a possibly irrelevant counter-example, MapMate automatically makes the determiner = recorder, but when I import records from that system I automatically strip out the determiner name(s) if identical to the recorder(s).

**Comment by kitenetter** [comment]
I think it was me who raised this question, and I think I did so because I have got so used to MapMate's system of always filling in the Determiner field even if if is the same as Recorder. I think there is an argument to be made for explicitly stating who the Determiner is, rather than assuming it is the Recorder unless stated otherwise. However, it is not an argument that I feel strongly about, so no need to clutter the records from the app.

iRecord is somewhat inconsistent with this. Records added via "Enter a casual record" do tell you to leave the Determiner blank unless it is different to the Recorder, but records entered via "Enter a list of records" pre-populate both Recorder and Determiner with the logged-on user's name.
