### ISSUE TITLE
Add a DAFOR scale option to general list sample abundance attribute

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#173]
From Mark Gurney: 

> Option of DAFOR for Abundance in general surveys? We record plants using DAFOR, but not in 1km squares, so we would use General survey for them.

**Comment by japonicus** [comment]
I think that could be useful, but there are some pitfalls. It would need to be clear that the DAFOR terms have specific technical meaning. The plant recording form is fine as it requires a letter code, e.g. 'R'. I would be worried if the general recording form had, for example, a tick-box labelled as 'Rare' because that would be open to accidental misuse by people who didn't intended to use the DAFOR scale.

Splitting hairs, another issue is that DAFOR applies to a defined survey area - so is well suited to gridded surveys, but might be invalid for a centroid-based casual record, because in that case it's not clear what survey area is referred to.

**Comment by kazlauskis** [comment]
Thanks @japonicus, good points. To your second suggestion about defined areas. We are adding a Plant-like survey to the iRecord App. It would not restrict to Monads/Tetrads but would still have a survey-level location (most likely a gridref in the UK).

FYI here is [the demo](http://irecord-app.herokuapp.com/demo.html) - long click on the 'Plus' button to record surveys.
