### ISSUE TITLE
App map references inconsistent between Sample and Occurrence

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#196]
Transferring from [iRecord issues list](https://github.com/BiologicalRecordsCentre/iRecord/issues/867).

David Hepper reported:
A new recorder has used the iOS App to record several species of dragonflies at UEA in Norfolk but didn't enter his sightings until he had travelled home to Northumberland. The geolocation has gone wrong, though he says he used the map when entering them to override the default GPS entry. Is this user error or a fault in the App?

Example:

    Record IDs: 14006581 .. 7
    Survey: iRecord App General Survey
    Parent sample > Gridref_calculated: TG19690703 [this is correct]
    Sample > Gridref_calculated: NZ2084 [this is incorrect - Northumberland]
    Location source: gps [this is incorrect if he adjusted the map]

I have asked those concerned not to make corrections until after diagnosis!

@kazlauskis  replied:

In the iRecord App for the General Survey we haven't developed the functionality to automatically update all child samples when manually changing the parent sample location. This has been done to the Plant Survey which is in the app though so we could follow the same approach here as well.

**Comment by DavidHepper** [comment]
Bump.

**Comment by kazlauskis** [comment]
There is a setting in the app called "Geolocate Survey Entries", which is turned on by default. This allows capturing exact locations for each species occurrence within a survey list. If a user wants to enter a species list away from the actual survey location (e.g. at home), then switching this setting off would disable the GPS for each occurrence. The user can then use the map for each entry, otherwise, entries would default to the parent sample location.
