### ISSUE TITLE
Fix user session after changing credentials on the website

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#221]
At the moment, if the user changes the password or email/username on the website then the app cannot upload any data without re-logging in with the new credentials. To properly fix this, the app should be using an OAuth2 authentication that is available in Drupal 8+ systems.

**Comment by kazlauskis** [comment]
@BirenRathod what is the current roadmap for the iRecord website upgrade to Drupal 8+?

**Comment by BirenRathod** [comment]
@kazlauskis irecord website has already migrated to Drupal 9. it is in testing phase at present. once everybody, I will put is on live but not sure when. you can find all discussion here -> https://github.com/BiologicalRecordsCentre/iRecord/issues/980 & 
test site here -> https://test-brc-irecord.pantheonsite.io/

**Comment by BirenRathod** [comment]
@kazlauskis About oauth system , it is generating lots of php error messages, which I mentioned below. Can you resolve it please? I'm not sure, it is due to combination of old version of oauth with indicia api v2 or only due to indicia v2.
User notice: Key file "file:///files/private/public.key" permissions are not correct, recommend changing to 600 or 660 instead of 770 in League\OAuth2\Server\CryptKey->__construct() (line 59 of /code/vendor/league/oauth2-server/src/CryptKey.php)
#0 /code/web/core/includes/bootstrap.inc(312): _drupal_error_handler_real(1024, 'Key file "file:...', '/code/vendor/le...', 59)
#1 [internal function]: _drupal_error_handler(1024, 'Key file "file:...', '/code/vendor/le...', 59, Array)

**Comment by kazlauskis** [comment]
Thanks, I am aware of this. It is a Pantheon limitation https://pantheon.io/docs/modules-known-issues#simple-oauth--oauth-20

I have applied the patch to fix these errors but the issue here is that the `oauth2-server` module looses the patch with the website upgrades - it is installed in the `vendor` folder.
