### ISSUE TITLE
Add activities to General Survey

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#222]
At the moment, the app allows to send records as part of iRecord activities. This is limited to the single-species survey only and we should enable this to the General Survey too.

**Comment by kazlauskis** [comment]
@johnvanbreda at the moment, for an app to fetch an activity from iRecord (using `library/groups/groups_for_app.xml` report) the activity must have an **iRecord App data entry** form (`enter-app-record`) attached in the activity settings. By enabling the General Survey to use activities the records from the app will now also have `enter-app-record-list` webform attached and not just the `enter-app-record`. Are there any implications of this?

**Comment by johnvanbreda** [comment]
@kazlauskis There are a few tweaks to make sure that enter-app-record-list is treated the same way as enter-app-record (e.g. the CSS styles applied to the activities page). I've done that now.
Also the groups_for_app.xml report needs to have a small change to allow you to submit a comma separated list of paths in the path parameter which I'll try and get done later.

**Comment by kazlauskis** [comment]
Thanks, does this mean I should change the report request with something like this? `groups_for_app.xml?path=enter-app-record,enter-app-record-list`

**Comment by johnvanbreda** [comment]
Correct, but not yet...

**Comment by kazlauskis** [comment]
Another question, can the app submit records to activities that will have either of these? like a single-species record can go to an activity that has `enter-app-record-list` form only and vice versa, General Survey to an activity with `enter-app-record` form?

**Comment by johnvanbreda** [comment]
Hmm - I presume you don't really want the app to only be able to submit casual records sometimes, and lists other times, depending on the selected activity? In which case I think we should continue with the idea that the app is enabled by adding the enter-app-record form, and once enabled, both the list and casual record modes are always available. It will be simpler for the user to configure and less confusing inside the app I think?

If so, then I need to make a small tweak so that the enter-app-record-list form behaves nicely even though it is not actually linked to the activity. Let me know @kazlauskis.

**Comment by kazlauskis** [comment]
Totally, I was thinking along the same lines. The user selects an activity in the app and then can use any of the 2 supported surveys. 

As an idea, in the future, maybe other surveys could be supported too.

**Comment by johnvanbreda** [comment]
@kazlauskis - that's done. You don't need to change your call to the report `groups_for_app.xml?path=enter-app-record`, it should be OK to edit records on the enter-app-record-list form now even though that form isn't explicitly linked to the activity.
