### ISSUE TITLE
Urgent: a common species has vanished: Sympetrum striolatum

### ISSUE THREAD

**Issue by DavidHepper** [NERC-CEH/irecord-app#223]
The dragonfly species _Sympetrum striolatum_ Common Darter has now disappeared from the iRecord App. This is now urgent because its flight season has started. There is clearly a problem with UKSI - the same issue occurs on desktop iRecord whenever(?) UKSI is updated. The following may help: 
https://github.com/BiologicalRecordsCentre/iRecord/issues/993 
and more detail in the earlier 
https://github.com/BiologicalRecordsCentre/iRecord/issues/909
David

**Comment by johnvanbreda** [comment]
I think this wasn't a problem with UKSI, but with changes applied after a UKSI update when editing the attribute data associated with Pantheon species lists. I fixed the underlying problem back in February but if the app last pulled the species list from the warehouse copy of UKSI before then it could well have been missing.

**Comment by kazlauskis** [comment]
@DavidHepper we currently have a _Sympetrum striolatum ssp. striolatum_ in the app, do you say we should also have a non-subspecies option? I can see the 'Common Darter' common name is missing.

**Comment by DavidHepper** [comment]
The ssp is no longer required and may be marked not to be available for selection, since we resolved (using DNA) the status of _Sympetrum nigrescens_ as a local variant of _S. striolatum_, rather than a separate species or subsp.
We really need 'Common Darter' back for striolatum, please.

**Comment by kitenetter** [comment]
@DavidHepper do you want me to make the ssp. unavailable for data entry on the website? And can you ask Chris Raper to mark it as redundant in the UKSI (which will be the best long-term solution)?

**Comment by DavidHepper** [comment]
@kitenetter Yes please, if it's easy and low-risk. The issue with Common Darter comes under Panic Mode but we're holding off name changes until the autumn. There are a several updates to UKSI that we need to request but getting these right is important and we don't collectively have time just now.

**Comment by kitenetter** [comment]
The sub-species is now marked as "not for data entry" and will shortly be removed from the iRecord data entry forms. This does not of course address the issue with the app.

@kazlauskis in case it helps, this is the scientific and English name that should be available in the app:

[Common Darter taxa.xlsx](https://github.com/NERC-CEH/irecord-app/files/6895414/Common.Darter.taxa.xlsx)

**Comment by kazlauskis** [comment]
The app doesn't cherry-pick and modify the species themselves. It simply displays whatever the latest UKSI (Indicia managed) list is available for it to download. I am not sure what the "not for data entry" flagging means but in case the species report that the app uses doesn't reflect this then the app wouldn't change this then. Looking at the iRecord search, it does produce the Common Darter so it might be OK since the app and the forms share the same UKSI list.

The species report for the app needs some fixing so I have asked John to have a look at it. Once that is done then it should be straightforward to update the dictionary with the latest one and push out the update.

**Comment by johnvanbreda** [comment]
@karolis I've sent a separate message about the species report. The not for data entry flag is a way of blocking a name from being included in searches during data entry, whilst still allowing existing records of the taxon to persist. Not for data entry taxa are already excluded from the app species report so you should be OK.

**Comment by kazlauskis** [comment]
@johnvanbreda thanks, I have pulled in the latest report data.

@kitenetter the _Sympetrum striolatum_ now appears correctly in the app but the **Common Darter** common name is still missing. Is there something you can do to enable in the Indicia UKSI list?

**Comment by kitenetter** [comment]
The name "Common Darter" appears on the website, and I couldn't see anything unusual about the way it is set up in the Indicia table.

Sorry, this will have to be another question for @johnvanbreda

**Comment by johnvanbreda** [comment]
Although the name exists, it is only the preferred common name that gets passed to the app. Since the last UKSI update, Sympetrum striolatum has had no preferred common name.
I've fixed the data so you can try pulling the names again @kazlauskis. I'll also have a look to see if I can spot the underlying problem in UKSI.

**Comment by kazlauskis** [comment]
Thanks John, I've pulled in the latest report and the Common Darter now appears in the list.

@DavidHepper this will come out under v5.4.1 update sometime shortly after app stores approve it.

**Comment by DavidHepper** [comment]
Yes, I checked this yesterday and both common and latin names are working correctly. Thanks for your prompt attention. I'd have been bombarded with complaints otherwise.
