### ISSUE TITLE
Text from v6 feedback

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [NERC-CEH/irecord-app#240]
Hi @kitenetter, 
1. Would it be possible to get "Auto ID" and "Verification section" text for the "Help page"?

2. From feedback: Not sure why the “business” icon is needed. If it is intended just as an icon for location, can the tooltip text “business” be removed? (Or does that only appear on the web demo?)

Yes, "business" only appears in the web demo. It won't show on the app.

We can change the icon to something else like:

  1.https://www.flaticon.com/free-icon/adress_2776064?term=adress&page=1&position=8&page=1&position=8&related_id=2776064&origin=style
  
  2.https://www.flaticon.com/free-icon/maps_2294170?term=adress&page=1&position=12&page=1&position=12&related_id=2294170&origin=style
  
  3.https://www.flaticon.com/free-icon/address_3969502?term=location%20adress&page=1&position=5&page=1&position=5&related_id=3969502&origin=style
  
  4. ![village](https://user-images.githubusercontent.com/53124253/203495330-4365c5f7-73fc-451e-9b08-ac88b459604b.png)

**Comment by kitenetter** [comment]
@Vilius-Stankaitis I'm happy to write some text but will struggle to get on to it before the middle of next week, will that be okay?

My preferred icon from that list is no. 2, but no. 4 is also good. No. 3 is fine if we need to keep it simple. Not keen on no. 1.

**Comment by Vilius-Stankaitis** [comment]
Yes, perfect! 

Thank you

**Comment by kitenetter** [comment]
@Vilius-Stankaitis text and some screenshot images for the two proposed Help pages is here:

[iRecord app Help text.zip](https://github.com/NERC-CEH/irecord-app/files/10126890/iRecord.app.Help.text.zip)

There are some queries in the comments to the text.

**Comment by Vilius-Stankaitis** [comment]
@kitenetter Thank you for the text. 

The app beta version should be available now. Would be possible if you could test if the Verification and AI flow are correct?

**Comment by kitenetter** [comment]
@Vilius-Stankaitis yes, I do have now have v6.0.0 on my phone, very exciting!

So I can test the flow through these routes, and I think I will need to revise the Help text, will do that later today.

When you first use the app, the home page displays:

![image](https://user-images.githubusercontent.com/16039111/205068626-7e856552-1996-4c6b-8781-e6a5fd1ca13d.png)

which gives no indication that it is possible to start by adding a photo, rather than by using the + button. Can this text be changed to:

You have no finished surveys.
Press + to add record details, 
or press [camera icon] to add a photo first.

**Comment by kitenetter** [comment]
Using the beta version on my Android phone, if I add a photo and the app suggest multiple IDs, I can see the first three, and I can see that at least one more suggestion is available, but I can't scroll the suggestions to get past the first three.

**Comment by Vilius-Stankaitis** [comment]
Could you try with two fingers swiping to the left (like zooming on the map)? This happens because the AI suggestions block is wrapped in another sliding component (Gallery). 

I will create a new issue ticket for this, to see if it is possible to improve UI.

**Comment by kitenetter** [comment]
Yes, it works fine with two fingers.

**Comment by kitenetter** [comment]
@Vilius-Stankaitis I have revised the auto ID Help text, but for the verification Help text I need to understand how the verification notices will work in the app. I've added some test records today to see what happens when they get verified or queried, but I'm not sure when or how the notification will appear in the app. I guess it may not come through until tomorrow as I usually get notifications just once a day.

Let me know if there is any more information available on how the notification process will work, but otherwise I'll see what happens tomorrow.

**Comment by kitenetter** [comment]
I added two records to the app yesterday, and then on the website I marked one as "accepted" and the other as "queried". I have now received the usual website email notification about the accepted record (but nothing yet about the queried record). However, I can see nothing in the app to notify me about either record.

Should I be seeing something? I don't have the experimental features switched on, would that make a difference?

**Comment by kitenetter** [comment]
Here is the revised Help text for the image recognition:

[iRecord app Help text_image_rec_v2.zip](https://github.com/NERC-CEH/irecord-app/files/10142177/iRecord.app.Help.text_image_rec_v2.zip)

I can't revise the verification one until I understand how the notifications will work.

**Comment by Vilius-Stankaitis** [comment]
That is strange. I will look into this. Experimental toggle is not required. Also you will not get notifications from "queried" records.


After record is verified should happen 3 things:

1. Pop-up
![Screenshot 2022-12-02 at 20.56.59.png](https://zube.io/files/nerc-ceh/a9117ffe31b74349e5fb8c2e1b3bf8e6-screenshot-2022-12-02-at-20-56-59.png)? 

2. Verification icon 
![Screenshot 2022-12-02 at 20.58.06.png](https://zube.io/files/nerc-ceh/69384cdcf49aca50cc1e23c0a79bcf72-screenshot-2022-12-02-at-20-58-06.png)  

3. Verification message 
![Screenshot 2022-12-02 at 20.52.01.png](https://zube.io/files/nerc-ceh/c6151db46bb90284c516714426d87b7f-screenshot-2022-12-02-at-20-52-01.png)

**Comment by kitenetter** [comment]
I just started adding a new single record to the app. I added the species name, and having done that the pop-up has now appeared to tell me that the previous test record has been rejected. There was no sign of any pop-up until I started adding a new record.

That doesn't seem to be the best sequence, because it is a much longer delay than 30 minutes, and also if I want to see the verification details I will have to come out of adding the record I'm part way through.

Also, it would be good to send people notifications of records being queried, as many verifiers find that iRecord users ignore record queries and we are trying to make them more prominent.

Will app users have any control over whether the verification notifications are shown or not? People who use the app for recording moths, for instance, may have a lot of records all verified at once and I don't know if that means they will then have to dismiss lots of individual notifications.

Also, the verification notification seems to have some auto-generated text that says "we do not think this is ... species". This could be misleading, as the verifier may have rejected the record for other reasons, and may have added explanatory text as a comment with their verification. If we are not able to include the comments I think it would be better to use a deafult text that says "Thanks for sending in your record. A verifier has marked it as "not accepted" in this case. Please log in to the iRecord website to see any additional information that the verifier may have provided."

Also, if I click on the "DETAILS" button it says it was verified by "Kazlauskis, Karolis" today, so is this the result of something you have done, rather than being linked to the verification decision I added a few days ago? If it is your verification then I may be misunderstanding the comment text - did you add the comment about "We do not think ..."?

Sorry, more questions than answers! I will try another test record and will verify it myself to see what happens.

**Comment by kitenetter** [comment]
Okay, so now I've looked at the rejected record (ID 28834987) on iRecord, and I'm even more concerned. I originally rejected it on 1 December, and added a comment. This is shown in the comment thread for the record. However, Karolis' name is now given as the verifier, but without any further addition to the comment thread, i.e. it now appears that the comment thread is contradicting the record status.

I don't know if this is because Karolis made a direct database update to add a second record rejection to the record?

In any case I am now very nervous about how this is working.

**Comment by kazlauskis** [comment]
Hi Martin, yes I wanted to re-trigger the existing record's status so manually changed it myself. Looks like you're getting the updates now. If you could review that the messages displayed in the app make sense to you then that would be super good 🙏. We have originally developed this for Bloomin' algae app and so the texts and verification comments are in their basic form. I suggest playing with different verification statuses of your existing records to see all the variants of texts.

I'll create a new ticket for queried records.

**Comment by kitenetter** [comment]
The new record I added is ID 28858967. I verified it on the website shortly after, and the notification has appeared promptly within the app.

The message in the app is an auto-generated one ("Thanks for sending in your record") so it looks like we are not able to pick up on any comment that the verifier may have added. On the one hand it is really good to be able to display the record notifications within the app (because app users may not ever log in to the website and see what happens to their records). On the other hand, it is a shame and potentially misleading that we're not able to include any comment from the verifier, especially where records are being rejected (and this does mean that verifiers may spend time adding comments that are never seen, although arguably that is the position we have always been in for the app records).

It would be really good if we can find a way of notifying app users of queries over their records, but that will only work if we can include the comment text associated with a query.

Assuming that for now all we can do is notify the verification decisions without any comments then I think that is good to do and should go ahead.

Remaining questions for @kazlauskis -
1. If I submit 50 records from the app that all get verified, will I receive 50 individual notifications within the app?
2. When the notification arrives, it has a tick box for "Do not show again". If I tick that box does it prevent any further notifications within the app? Is there a way of subsequently unticking it? And does it interact with the notification permissions in the website user account?

**Comment by kazlauskis** [comment]
1. You should see one notification. The pop up aggregates all the updates to your records since the last synchronization. It does so at 15min intervals so it can potentially be split into 2 notifications if some of the 50 records were verified later than others.

2. Ticking means you won't see the pop up anymore. The records will still update in the background but the pop up won't appear. If the checkbox is ticked then there is no way to reset it other than reinstalling the app or resetting all of its data in the app settings page. This pop up isn't tied to the website permissions in any way.

**Comment by kitenetter** [comment]
Here is the revised text for the Help section regarding verification and notifications.

[iRecord app Help text_verification_v2.zip](https://github.com/NERC-CEH/irecord-app/files/10176637/iRecord.app.Help.text_verification_v2.zip)
