### ISSUE TITLE
Create a Bryophyte Survey form

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#247]
It woudl be useful to have a ‘Bryophyte survey’ option (as an alternative option to ‘Plant Survey’) to include the various fields that come up on the casual record form when a bryophyte species is entered.
@DavidRoy could you indicate what priority this has please?

**Comment by claire-halpin** [comment]
The British Bryological Society is reviewing its recording methodologies and records database at present. One option would be to use iRecord, but for this we would really need a Bryophyte survey. I think there would be quite a few bryologists keen to use this if the option was available, and it might encourage some newer members to start recording before they would otherwise.

**Comment by kazlauskis** [comment]
Hi all, I can add the bryophyte survey this month. Do you have a specification for it?

**Comment by DavidRoy** [comment]
@Sam-Amy can you liaise with Oli and the BBS to define the specification

**Comment by Sam-Amy** [comment]
Yes, I am doing this.

**Comment by sacrevert** [comment]
@kazlauskis Currently I think the best thing to do is just to copy the existing form at https://irecord.org.uk/enter_bryophyte_records

BBS Council has just decided to convene a working group on the future of the BBS Database, and so I don't think it is appropriate to putting lots of energy into reviewing these options now, as it may be that a non-iRecord (but perhaps still Indicia) solution is decided upon.

**Comment by DavidRoy** [comment]
Thanks for the update @sacrevert.

Regardless of the BBS decision, I think it's useful and would support an improvement to the options to record bryophyes in the app.  I agree that mirroring the irecord website form is a good next step

@kazlauskis are you ok to proceed on that basis?

**Comment by sacrevert** [comment]
Cheers. The reasons that I don't want a full review of the options now is that it will impact data exchange with any new system, and I don't want to preempt that. We can review the options here in the future in light of BBS solution

**Comment by Sam-Amy** [comment]
@sacrevert Bear in mind that the various forms already available to record bryophytes (casual record on web or app/list of records on web or app, web bryophyte form) all have slightly different combinations of fields at present anyway. One thing possibly worth considering is that the web bryophyte form doesn't currently have a field for 'identified by', whereas the Plant Survey form on the app does (which means it is available to add later in iRecord) - would this be worth adding?

**Comment by sacrevert** [comment]
I'd prefer to just copy the bryo form at present, as even that brings up questions: should we separate det/conf? What does that mean for future data exchange with a database including legacy (Oracle) data? Is "identified by" the same as det or conf or both?

**Comment by kazlauskis** [comment]
We added dynamic species attributes to the app in 2017, and at that time, we also included bryophyte attributes. We used the _enter_bryophyte_records_ iRecord form as a template at that time, too. This form has slightly changed since that time (now it also includes the "Microhabitat" option, maybe something else?), but users can already capture the bryophyte information in the app. I can create a separate survey, but if this captures exactly the same information as the app already allows, I'm curious how useful this will be.

<img width="414" alt="Screenshot 2023-09-12 at 15 06 12" src="https://github.com/NERC-CEH/irecord-app/assets/7383162/7fa1d74c-7732-44fe-90fd-98b4aad481a9">

**Comment by sacrevert** [comment]
Thanks @kazlauskis I'd forgotten that. What's this issue about then?

**Comment by kazlauskis** [comment]
@Sam-Amy 🤔

**Comment by DavidRoy** [comment]
I think this issue is about the 'Plant Survey' mode, i.e. grid square lists?

**Comment by sacrevert** [comment]
Ok, so all we are doing is adding a bryo option to that functionality, with the same dynamic attributes as the web form. Cheers

**Comment by Sam-Amy** [comment]
Yes, the Grid Alert option in the Plant Survery was the catalist for this issue - sorry, I should have been more clear.

**Comment by kazlauskis** [comment]
Since the app's dynamic attributes also extend to the "Species List" survey, the app currently allows users to compile a bryophytes list for a given square. This is not exactly the same as a dedicated plant survey, but it is very close.

Plant survey:
<img width="410" alt="Screenshot 2023-09-12 at 15 29 58" src="https://github.com/NERC-CEH/irecord-app/assets/7383162/2a29140d-9697-4a2f-8a5a-09e544b6f189">

Species List:

<img width="411" alt="Screenshot 2023-09-12 at 15 31 21" src="https://github.com/NERC-CEH/irecord-app/assets/7383162/d37bc88b-a764-4658-b810-ed6addb520b7">

If this is about the grid alert, then we are planning on adding this as part of this ticket: https://github.com/NERC-CEH/irecord-app/issues/246

**Comment by sacrevert** [comment]
Ok, cheers! Maybe we can close this then @Sam-Amy ?

**Comment by kitenetter** [comment]
Just to pick up on the question from @sacrevert 

> Is "identified by" the same as det or conf or both?

On many iRecord forms we have opted to use "Identified by" as a more user-friendly way of saying "Determiner". In any case, these two are the same.

I can't think of any cases in Indicia where we use the concept of a "Confirmer", although notes about additional agreements with a determination can of course be included in any comments attached to the record.

My interpretation of "Verifier" is that this is the person who makes the decision as to whether the record is acceptable for the recording scheme that they represent. In my view this is not quite the same thing as confirming the record - a verifier may not be able to confirm a record (because there is no evidence on which to do so) but may still trust the recorder and/or determiner enough to accept the record.

Personally I think that all recording forms and apps should allow both a recorder name and a determiner name (= Identified by) to be given, although the determiner is optional (and if left blank the recorder is then assumed to be the determiner).

Let me know if my zoological interpretation of the above is incorrect from a botanical perspective!

**Comment by sacrevert** [comment]
Thanks @kitenetter 
That was not so much a query, as a rhetorical question illustrating some things we need to think about when creating a new BBS database that allows both the import of the Oracle data, and, potentially, exchange with iRecord if iRecord is not the solution chosen.
