### ISSUE TITLE
Post into recording groups (activities)

### ISSUE THREAD

**Issue by johnvanbreda** [NERC-CEH/irecord-app#40]
It would make the app much more useful if it were possible to post records into any recording groups I belong to on the main iRecord site. For example, we could direct Garden Bioblitz members to the app and they could post their records into the bioblitz using the app. Although in a perfect world the app would be able to pick up the attributes from the appropriate recording form, in many cases (such as biolblitzes) the exact attributes collected are less important than the participating so using the standard app survey dataset would be fine. 
Ideally:

- It should be possible to set your current group/activity then remember it from record to record during a recording session, so that mistakes aren't made by forgetting to select the group.
- A group should have a flag to enable app functionality, so people don't try posting records in groups that have a very specific recording method and set of attributes.

**Comment by kazlauskis** [comment]
I am not too familiar with recording groups, but it sounds like a good idea. Could you expand on your last point about the **group flag**.

**Comment by johnvanbreda** [comment]
Ok, so in iRecord people can create "Activities" (which are called Groups elsewhere), see http://www.brc.ac.uk/irecord/activities/list. These activities/groups allow people to worktogether for a recording project. It could be anything from a national scheme or society, through to a group of people working on a local nature reserve together, or in my case the Garden Bioblitz. Groups allow these people to nominate administrators who can control who belongs to the group, which recording forms and which reports are available for the group. My idea is that the group admin can tick a box on the group edit page (http://www.brc.ac.uk/irecord/activities/edit) to enable accepting records from the iRecord app. Some groups may not want to accept app records, for example if their recording methodology is quite specific so the records would not fit their dataset. But for other groups like the Garden Bioblitz, we don't have a very specific need for the set of attributes captured, so app records would be great and we could tick the option to enable app submitted records. 
Since there is already a way of configuring which recording forms are available for the group, having thought about this we probably don't need a special flag. If we create a page on iRecord for editing app records (which has the correct survey ID, attributes etc) then we can use the fact that this page exists for the group to turn on submission from the app. So, I think the changes required are:

Add a recording form to iRecord which links to the same survey dataset and has the same attributes as the app. The path could be something like submit-app-record.
In the app, set the sample.input_form field value to submit-app-record for all submitted records. This way when you edit them in iRecord you will get the correct data entry form. I think these 2 points should be done anyway, rather than editing being done in the standard enter-record-list page.
Tick the box on the edit page for this form so that it is available for groups so that group admins can turn on the app recording form.
In the app, run a report which checks which groups the user belongs to (groups_users table) where the group is linked to the app recording form. This will give you a list of records from the groups table with an ID and title. This can then be shown as an extra field on the data entry form so you can submit records into the group. Or, better still, the user could select their activity on the home page and this setting will stick until they change it.
Therefore, if a user has selected a group/activity to post records into, the record would be saved with the samples.group_id field field in to the ID of the group. The record will then appear on group reports that filter on this field.
When submitting a record, if there are any groups

**Comment by kazlauskis** [comment]
OK, sounds good. You are right about submit-app-record input form, this should be added and linked anyway. 

I wonder if a person can submit a record to a group without first joining it, would the records reach the group? I am looking for the bare minimum that is needed to make this functionality work and that is to eliminate the user groups server fetch (though this could be easily done).

This all would be quite easy to implement. In the app settings you could add a Garden Bioblitz tick box that would set an attribute on user model. Then inside the app configuration file which is a JSON object, in *morel.sample* object add a sample attribute check:
```javascript
group_id: { 
    values: function (){ 
        return userModel.get('recording_group');
    }
} 
```
and force this check by adding this to sample create:
```javascript
sample.set('group_id', true);
```

**Comment by johnvanbreda** [comment]
For some groups they want to control membership so you shouldn’t post without joining. The Garden Bioblitz doesn’t actually care though, so if you set sample.group_id to the bioblitz group’s ID it would be fine even if they don’t join.
Agreed, we could implement a simple tick box as you suggest. But this approach would always be present even when the Garden Bioblitz is not running. Also it wouldn't accommodate other groups which want to use the app. My final concern is that the tickbox hidden on app settings would be difficult to explain to participants and they would miss it, therefore submitting records which aren't added to the group. Is there a way of making the setting more prominent?

**Comment by kazlauskis** [comment]
Good question, I am not sure where it would fit in best. I agree, we should keep it high profile. I also think it shouldn't be on the record edit page since it already has enough interface options for the user to digest. Plus this isn't a per record functionality, but more of a user setting.

There are two places where a setting can go - user or app model. The app model is where the device+app specific settings are stored, app preferences in other words. They are not synched with the server and so opening the app on another device with the same user account would not carry over the setting. The user model is where the information is carried over - exchanged one way or both directions -  with the server (iRecord/Indicia Warehouse).  There isn't much in user model yet. Just user name, surname and user secure login secret. User groups are certainly what should be synced with the iRecord, so it should be added to user model. Same would be for user favourite/saved locations, favourite taxa, counties etc.

There is no place for user settings yet, only app settings page. So we could add one and we could have a link to it somewhere on the home page (records list) header, next to the menu button or camera.

Also, once the activity is selected, it could be reflected on the record edit page and maybe the list entry with an icon or some text, so that the user knows the record belongs to some group. Say, you open the app, click on the user icon at the top of the list, select 'Garden BioBlitz' open a new record and it says 'Garden BioBlitz' at the top of the header, rather than 'Edit' or something.

What do you think of it that way?

**Comment by johnvanbreda** [comment]
The currently selected group doesn't need to be synced with iRecord - it's more of a state flag for the app itself. So I think it is an app setting logically, though it does need to be easily accessed from the app header rather than buried in the settings menu.

Are you happy with the idea of querying the warehouse to find which activities a user belongs to that have the app recording form linked to them? You mentioned trying to keep it simple but without this we will be unable to control the available activities without issuing new app versions. If the app does this query and finds there are some results (such as the Garden Bioblitz) then you could add a new icon for picking the current activity into the green header bar. This would drop down a selection list with "iRecord" always being present as the first activity. When an activity is picked, then the records list would be filtered and any records submitted would be tagged with that group ID. Also when an activity is picked other than iRecord, the activity title could be displayed in the header bar alongside the icon. 

OR, an alternative approach. Don't have an app setting at all. Instead, if there are activities available for the user to choose from then the record edit page could have an extra row in it called Activity. This would force the user to pick from iRecord or one of the available activities and the record gets submitted with the appropriate group ID. The activity name can be shown in the record details on the list page. Also, the activity selection can be remembered so when you add the next record it keeps the same setting unless you change it.

**Comment by DavidRoy** [comment]
Karolis and I discussed this requirement briefly today.  Having read this issue thread, I'd be ok with the following.
1. The App header has a drop-down list of activities that the user has signed upto (populated by synching with the warehouse).  'iRecord' is the default value.  I assume that if a user has selected an activities (e.g. garden bioblitz) that then expires, the App will default back to the iRecord activity.
2. This is optional - but on the record details/edit page, the currently selected activity is reported to the user and they can change it here (it then become locked to that value and sets the home screen value)
3. The activity management remains on the iRecord website.

**Comment by johnvanbreda** [comment]
I agree with that. Appreciating that I (and the Garden Bioblitz) are the driving force behind this, are you planning to do this Karolis or would you like me to take a look?

**Comment by kazlauskis** [comment]
Alright, yes I would be happy if you gave it a go.

**Comment by johnvanbreda** [comment]
I've now pushed up feature-groups if you want to take a look. Its now working but with a couple of bits to finish off:
* I've not implemented any support for changing the activity when editing an existing record. It shows the activity on the record edit page but you can't change it.
* I still needs to filter out activities which are no longer active.
* If no activities are available then the list view displays the list-none template. Could this do with a link to help about activities?
* Activities controller API - I've put the main view in the API directly because I need to keep an instance of it for use when the refresh button is clicked. Is that acceptable?
* What do I need to do about test code?
* There was also the question about storing the activity title against the sample, even though its not an attribute to send to the database. Morel complains when I do this.
* I found when adding icons (e.g. the refresh and users icons) git's branching model doesn't
work very well when updating from master. I needed to grab a new copy and added the icons
again otherwise all the codes were messed up. Just something to watch for in future.

**Comment by kazlauskis** [comment]
Hey, that looks nice, I like it. A couple of details I would like to mention:

- I would like the activities button to be next to the menu (burger icon - 'pull-left' div). It comes down from the idea that there was originally only one (the Plus) button that was supposed to stand out from the rest of the header buttons, a clear indication that this is a next button to press once you open the initial page. Since then I have also added a camera button as this is just another way to start a record. Btw, I like your icon choice.

- I would display activity names only in the activities list - having descriptions looks good on an iPad, but on an iPhone 4 looks too cramped. You could try adding a description popup as a second button perhaps.

- Having the activities button on the home page, if the user has not selected any activities (other from the default one) I think there is no need to have a second way to change it on the record edit page. ie. only if the user has selected say **My garden birds** as activity, the activities button should appear on the record edit page. This would make the default recording page cleaner. 

**Some of your questions:**
*If no activities are available then the list view displays the list-none template. Could this do with a link to help about activities?*
- I am not sure if I got the question right. Yes, I believe we should write some short help about the activities and it could be a good place to link it to. 

*Activities controller API - I've put the main view in the API directly because I need to keep an instance of it for use when the refresh button is clicked. Is that acceptable?*
- Normally, views are disposable. It is best practice to re-render the view on the model change and so I try following that throughout the app. If I were you, I would simply listen on the activities model (collection) events in the view. Eg. no activities - show empty list view; new activity added/removed - re-render the view. Since you don't have a separate collection for the activities, you could listen to appModel 'change:activities' event (you might need to trigger that on ajax success - appModel.trigger('change:activities')).

*What do I need to do about test code?*
- I try to cover as much as I can with tests, almost TDD approach now, but there is still lots of code untested which I am planning to test eventually. It would be great if you tested the very core functionality and I could then add the remaining tests if you wanted.

As I said, I like it, looking forward to integrating it to the app :)

**Comment by johnvanbreda** [comment]
Hi Karolis
Thanks for the feedback.
1) Agreed - I've moved the button next to the "burger menu".
2) I'm not sure I agree as the activity description might be quite useful. I have, however, changed the layout to get rid of excessive padding on the right side, plus cut the string off after 1 sentence if it is long. Is that OK?
3) The default record page now doesn't show anything for records not attached to any special activity.

- Help - agreed, we could have a link to help from this page. But, we surely need a standard place to put this help information for the whole app? If not don't worry as the wording does explain things at least briefly.
- Activities controller API - I tried this but it starts to feel messy. There are event handlers etc and various references to the view which would need to be reconstructed. For example, the onExit method refers to the view, so if the view is disposed and recreated, this method must also be, and it is also referred to by the headerView.
- The view is in fact re-created every time the activities page is loaded so is disposable. It also has nice built in marionette functionality to self-update when I change the collection content so it seems a shame to not use this. All I am trying to do is _temporarily_ show a loading overlay when the refresh button has been clicked and it seems logical to me to keep the view to redisplay it after the loading overlay has finished.
- Tests - I've only just spotted the references to testing in CONTRIBUTING.md so I'll take a look now.

**Comment by johnvanbreda** [comment]
Hi Karolis
I've now added some tests for the app model changes.
Things still to do:

- Add the recording form to iRecord and use that as a filter for the activities which are to be made available
- Are you happy with the way the activities mainView is held in the API as described above?
- We need to store the activity's title (group_title) against the sample so that it is available for rendering in the record page etc. Currently, the sample model overrides the constructor and adds the value to the array argument passed to the Morel sample (args[0]['group_title']). This works OK in that the group_title does get saved in the Morel attributes for the sample, but Morel puts a warning on the console that the group_title is not a recognised key (app.js:34851 Morel: no such key: group_title). Obviously it would be nice to tidy this up. Basically we need a way of storing a piece of data against the sample which gets saved to the local storage but which is not actually sent as part of the submission to the warehouse.

**Comment by kazlauskis** [comment]
Hi John,

- *Are you happy with the way the activities mainView is held in the API as described above?*

Eventually we will have to refactor this to match the rest of the code, but don't worry too much about it now, I will look into this later.

- *We need to store the activity's title (group_title) against the sample*

You can store extra attribute information without submitting it to the warehouse, which is what is happening now - Morel finds the sample attribute 'group_title', but no warehouse ID so it complains. I will write some updated Morel docs once I find some time, but here is a quick explanation on how it works. 

Within the app storing warehouse IDs for both attributes and their lookup values is not very human readable when you are working with your sample/occurrence data. So Morel gives an option to map your attribute names and attribute values to something else than a digit.

 On a record submission every stored sample or occurrence attribute is checked against the configured values which are stored in app configuration. Each **key** (ie. attribute) can have an **ID** which is the warehouse ID for that attribute and also optionally **values** object . In the values object there are _name-value_ pairs for the attribute lookup values, so for example, occurrence stage attribute key is configured as such:
```js
 stage: {
        id: 106,
        values: {
          'default': 1949,
          'Adult': 1950,
          'Pre-adult': 1951,
          'Other': 1952
        }
      }
``` 
so if the stage attribute is saved as _**stage**:adult_ within the occurrence, then it would be translated to _**106**:1950_ upon submission to the warehouse.

Now there are cases, like yours, when you want to have a more dynamic attribute values that are custom preprocessed upon submission, in such a case you can define your values object as a function like that:
```js
 stage: {
        id: 106,
        values:  function(value){
          //modify the value here
           return value;
        }
      }
```  
I do this thing for occurrence taxon and sample location, where for the taxon attribute I store warehouse id, taxon common name, scientific name, its informal group id etc, but only the warehouse id is used when sending to the warehouse. 

```js
 taxon: {
        values: function (taxon) {
          return taxon.warehouse_id;
        }
      }
```

**SO**, I hope you are still with me haha, all you need to do is to add this to the sample configuration:
```js
 group_id: {
        values: function (group) {
          return group.id;
        }
      }
```

**Comment by johnvanbreda** [comment]
Ok, that did make sense (I think!). I now store the group object in the Morel sample and retrieve the group.id in the config for retrieving the stuff to send to the warehouse. So I think that's OK.

I'll sort out the recording form tomorrow then I think this is ready for a pull request ??

I've not managed to run eslint yet - the plugin for my Atom editor seems to be not compatible with current versions and I'm getting errors when trying on the command line.

**Comment by kazlauskis** [comment]
No worries, I will eslint it. Great, we should merge it asap to leave enough time for apple review (7 days) and field testing.

**Comment by johnvanbreda** [comment]
OK:

- I've committed a changed to Morel to allow the sample.input_form to be saved.
- I've added a config for the input form to the app, and add this to the sample when it is constructed.
- I've started work on the input form in iRecord (http://www.brc.ac.uk/irecord/enter-app-record). Not finished yet, but that doesn't affect the app.
- I've submitted a pull request.

**Comment by kazlauskis** [comment]
I am working on it right now and should merge it sometime soon I think.

**Comment by kazlauskis** [comment]
Done :)  #87b97ac36b06cc38ddfd6f1926ffc7e8cb40af57
