### ISSUE TITLE
Location name required

### ISSUE THREAD

**Issue by AugustT** [NERC-CEH/irecord-app#45]
I am not allowed to submit a record without a place name. I don't want to have to give a location name if I have given to exact lat long on teh map

**Comment by japonicus** [comment]
This is partly my evil influence.

I think that omission of a place-name can seriously devalue a record (even if there is an accurate GPS'ed reference).  There is still a prevailing attitude (to some extent well-founded) among many verifiers that GPS alone can't be trusted.  Verifiers have little enough information to go on when checking a record and lack of a place name can often tip the balance toward rejecting a record.

Another problem is that it's hard to guarantee that a records exported from Indicia into other databases will retain any marker saying that the grid-ref came from a GPS - at that point it just becomes another anonymous, long grid-ref, subject to the usual concerns about typos or map-reading mistakes.

Finally named sites can make verifying records far quicker as the verifier may recognise a well-known site and not need to examine the map.

GPS can occasionally be inaccurate (and some of the implementations on smart phones may be quite poor) but a bigger problem is the assumption that the user enters a record while still on-location rather than half-way home on the M25 (true story from BTO).

I'm not sure if the app has the balance right with mandatory place-name's  - I certainly wouldn't want to re-enter a name for every record - but there is already an option to lock the placename and that could be streamlined further for records where the recorder hasn't moved far since a name was last applied.

**Comment by AugustT** [comment]
It seems that the issue you raise are all built on the premise that the GPS location given is untrustworthy and therefore the place name is required to verify the location.

I feel that a well designed app (as this is) addresses these issues. The app offers the use of gps showing a map of the location for verifaction by the user, or the map can be used to assign a new location. All the tools are in place to unsure the user does not get it wrong and that the GPS can be trusted.

With this design in place I don't see how a placename is going to be any more likely to be accurate, or correct. I have to admit that when I used the butterfly app (which also required a place name) i would just hash the keyboard as I get so fed-up. 'Place name' is so poorly defined anyway ('my garden', 'oxfordshire', 'wallingford' are all placenames for the same place).

In my mind this is an unnecessary obstruction to the user submitting a record and a duplication of the 'location' field.

**Comment by kitenetter** [comment]
This assumes that A) the user does do things such as checking the GPS location on the map, and B) that they are recording as soon as they see the species, rather than some time later when they may have moved away from the actual location. Although the app has the tools to allow a user to correctly assign a grid ref that doesn't guarantee that a user will always use the tools. In such cases, asking the user for a place name provides a checking mechanism whereby the verifier can gain a degree of confidence that hte user has the grid ref correct, or alterntively allow a verifier to query a record whose grid ref does not match its location name.

Also, consistent use of a place name is one way of grouping together a set of records, e.g. for a particular nature reserve, that may all have slightly different grid refs. Many recorders rely on this to be able to interpret and report on their records.

Rightly or wrongly many recording schemes expect a record to have a grid reference and a place name, and if one of those is missing the record is seen as being of poor quality and may even be rejected. It's possible to argue that this approach is outdated, but it will take time for this culture to change.

**Comment by AugustT** [comment]
Thanks @kitenetter and @japonicus 

As an outsider this still seems very odd. Essentially this field is added because you don't trust the GPS, if this is that case then don't include the GPS. The idea that a record would be rejected **with** a GPS because the location could not be guaranteed (not because it was obviously wrong) is mind-boggling to me, this is 2016!

I feel that in this day and age we should have confidence in GPS and that our application of it in well designed apps is rigorous and trustworthy. If this is not the case then we should make this a priority, #46, rather than enforcing place names.

**Comment by kitenetter** [comment]
I don't 100% trust the GPS, and have experienced GPS giving me incorrect locations in the past, although it does seem to have been better in recent years. But more importantly I don't 100% trust recorders to use GPS capability in a consistent way at all times, and although the location name can be regarded as redundant if the GPS is used correctly, we don't always know whether people are using the GPS correctly. I don't 100% trust **any ** method of locating a biological record, which is why some redundancy is useful!

NBN and others have for years been trying to drum into people the idea that there is a minimum set of standards that a high quality biological record should meet, and having a location name is one of those standards. The software that recording schemes use to manage records (MapMate, Recorder etc.) expects records to have location names.

Technological advances may well mean that we need to revisit the standards and work out an agreed approach to GPS-only data, with all the ramifications that will have for how data is managed and verified. But that will take time.

And I would emphasise that for people who record for fun, part of the fun is looking back at your records and remembering the places you've visited. My memories of visiting Wicken Fen National Nature Reserve are much more vivid than my memories of visiting TL561705.

**Comment by AugustT** [comment]
Okay. Let's assume we need to keep place name for all the reasons you state. Can we automate this step. 

Example:

I add a location by GPS. When my lat long is received and the location gets added to the record can the app (if it has internet) hit an API like this...

http://maps.googleapis.com/maps/api/geocode/xml?latlng=51.6022963,-1.1129377&sensor=true

...and auto fill the location? [cons: more work, needs internet, grasping at straws] 

> "I have a dream that one day my records will no longer be judged by their placename, but by the content of their GPS field" - Tom August 2016

**Comment by kitenetter** [comment]
Please no! Because if we automate the placename it no longer provides any redundacy, and in fact makes it harder to spot whether the recorder has correctly located their record. Also, automated gazetteers are usually ignorant of such things as nature reserve names.

On both iSpot and iRecord we started off using automated gazetteers, but got complaints from recording schemes because of the inability to cross-check, and from recorders because they didn't like the way that google automatically named all rural sites with the nearest A-road!

"I have a dream that one day the cultural significance of a place name will be seen as valuable in its own right, and not merely as an attribute of a spatial reference" :)

**Comment by AugustT** [comment]
The idea of the above is that it would be more noticeable to the user if they had entered the wrong location

**Comment by AugustT** [comment]
Haha, okay-okay, I'm clearly not going to win this one for the many good reasons you have given

**Comment by japonicus** [comment]
[edit: Martin's already better covered the main part of my answer, so have deleted that]

Rather than designing clever ways to circumvent manual assignment of site names, what we might concentrate on would be making the process as unobtrusive and efficient as possible.  Although typing on mobile phones is painful and slow, entering a site name should only take 15 to 20s **and should only generally need to be done once or twice in a recording session**.  If the app only prompts for a new name once the user strays too far (open to debate, but perhaps 2 or 3 km) from where the site-name was first used, then typically there would not be many name prompts needed.

A further refinement would be that at the start of a new recording session the system could automatically suggest names that the user had previously applied nearby, providing a pick list instead of requiring retyping of the whole site name (that shouldn't take more than 3 or 4s and be a couple of touch actions).

This may all sound a lot of hassle for collecting information that you consider redundant, but apart from the validation, trust and convenience reasons already mentioned, site names capture fine scale detail that a GPS centroid (e.g +-30m)  may miss: distinguishing between a road verge and the adjoining field; specifying which bank of a river I'm on (which might distinguish the county) and placing me inside or outside a reserve.  Of course that depends on the recorder, but it good to encourage people to do the right thing.

Incidentally, some of the problems with useless location names can be avoided by prompting for something like "Nearest named place" rather than "location" - so as to discourage people from answering "my garden".
