### ISSUE TITLE
Taxon names with numbers at start not found?

### ISSUE THREAD

**Issue by johnvanbreda** [NERC-CEH/irecord-app#57]
I tried adding a record of a 7 spot ladybird today but could not find the species name using any vernacular form. Is there a problem searching for names that start with numbers? I managed to add the record using the latin name.
In my opinion, the rules underlying search logic should be the same as iRecord's website. If you have enhancements to implement they ought to be implemented in both places so we keep the logic the same as many users are likely to toggle between the 2 ways of putting records in.

**Comment by kazlauskis** [comment]
For some reason the common name is **7spot ladybird**. There are still some taxon searching problems lurking here and there, but I agree the logic should be similar and that we should define it in detail. Currently, because of different requirements on the dataset formats some things might be a bit different.

**Comment by davidgenney** [comment]
Related to this query, I cannot find the moss Buxbaumia viridis on the app lookup list?

**Comment by davidgenney** [comment]
Related to this bug, I couldn't find the moss Buxbaumia viridis on the app lookup?

**Comment by davidgenney** [comment]
I've just checked, and Buxbaumia viridis doesn't appear on the web record entry lookup list either so this is probably not an app issue.
