### ISSUE TITLE
Multi occurrence samples

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#67]
This is probably for the future but I thought I'd mention it because it would help those of us who record a lot of species at a single location e.g. A list of lichens on a single tree.
At the moment we have to create a new record for each species recorded . The app is quite efficient but there is still a lag to save and enter each record. It would be good if there was an option to add multiple species to a single entry ie keeping all other attributes the same. So there would only be one submission at a location with multiple species. 
Does that make sense?

**Comment by kazlauskis** [comment]
Thanks for the suggestion. Would it be something like this [iRecord Dragonflies app survey mode](http://irecord.org.uk/dragonflies/#record/multi) ?

If so then it would be a multi-occurrence sample - one sample (location, date, comment), having multiple species occurrences. We have that in some of other apps, like the butterfly or grasshopper.

**Comment by MNSmith** [comment]
I would like to see this feature also.

**Comment by davidgenney** [comment]
Yes, that's just the sort of feature I was trying to describe, brilliant!

The ability to quickly add a lot of records with one set of location meta
data and then add individual species record notes is perfect and ideally
suited to the lichens and bryophytes I normally record. More often than not
you find a nice old tree and then spend 15 minutes recording the species
growing on it.

The British Lichen Society like us to record the substrate with a series of
standard codes, e.g. Cort, CFx, CTr would mean growing on bark of ash and
on the trunk. Free text works fine for this, particularly once the codes
are learnt by the phone's predictive text, but it would be great to
eventually have these codes in a drop down list...although I appreciate
that would be a lichen specific version like the dragonfly app. Similarly
the British Bryological Society have a few standard codes e.g. f. For
fruiting. Just some background for info and you can of course talk to Oli
Prescott about the bryophytes. I realise this is a future feature though
and you'll want to get the current version out there first.

I'm quite enjoying this app by the way...Great job.

**Comment by kazlauskis** [comment]
Regarding substrates, at some point we will be adding dynamic attributes #14, so once you select a lichen species, the attributes like number, stage etc would be tailored for lichen recording and include options like substrate selection.

**Comment by davidgenney** [comment]
That will be a superb feature. Thanks.

**Comment by MartinKleikamp** [comment]
Hi Karolis, great job, I analysed the code of iredord-app and why you finally choosed subsamples instead of multi-occurences? Would this also be possible via indicia module api? We had to modify the views and templates of course, would 10 hours effort with testing realistic?

**Comment by kazlauskis** [comment]
Hi @MartinKleikamp, at the moment the app sends a single occurrence sample for a general-recording mode, while the lists-recording (with grid alerts) does a subsample recording, because the records are all grouped in a "list". 

As far as I remember, the Indicia API module should support all types of recording - simple, multioccurrence and subsamples.

**Comment by MartinKleikamp** [comment]
Hi Karolis,
thank you for your response. We will change the list-recording to multioccurrences because actually in irecord-app there is only the one location from the survey sample copied to all subsamples. Also, our data in the warehouse is stored as multioccurrences.  Perhaps we will implement different locations for the subsamples type later, but in the moment there is no need for this.

**Comment by kazlauskis** [comment]
Hi @MartinKleikamp, sounds like a good choice. If your occurrences don't contain location or any other sample-level related info then keep it as occurrences.

**Comment by JimBacon** [comment]
Hi Karolis. I want to suggest some alternative language because, the way I talk about the data model, an occurrence never has location information. I know you know this but the way you have written it does not seem very clear to me.

In my words, the most basic record is a sample which would be measurements taken by a person at a place at a time.
A sample may have zero, one, or many occurrences which are the species observed at the sample place and time.
Samples may have a parent sample or, from the other perspective, a parent sample may have one or many sub-samples.

Using my language applied to your earlier comment, the app has two modes:

- general recording which sends a sample with a single occurrence and
- list recording where a parent sample (a 1km square?) has many sub-samples (with precise locations) which       each have occurrences (one or many?)

Have I got that right?

**Comment by kazlauskis** [comment]
Hi @JimBacon, yes, this sounds right. At the moment each subsample in list-mode holds only one occurrence. 

Yes, it can be a bit confusing :confused:
