### ISSUE TITLE
Past locations

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#83]
After a new location has been set to a record, the location is saved under **Past** tab where one could pick it up for any other record. It behaves somewhat like user favourite locations. 

I am not sure if by choosing from the past locations a user wants to copy only the location name or it's location too. I personally think that if I have a location with a name 'Wallingford' and this is where I mostly record I would not want to enter any new GridRef or click on a map every time I select my past location.

**Comment by johnvanbreda** [comment]
If you were in Wallingford wandering around creating records, you'd want to be able to pick up the past location name without overwriting the phone's current GPS. Otherwise you will get all records mapped to a single point on each site which is clearly wrong. Remember that most sites will cover more than one grid ref.
So I would only copy over only the location name personally.

**Comment by BlueCarbon7** [comment]
When editing a record, if you select 'past locations' and click on a cached location name, IF the record you are editing already has GPS based location information, this data should not be overwritten with the location data from the past location.

This behaviour is logical because by definition, using GPS when creating a record means you want the GPS location. Going to the past location tab simply enables you to easily set the location name (which is often the same across multiple records), whereas the location data itself may not be. 

If a user is adding multiple records at one physical location (so name and location data are the same on multiple records) the GPS will already be setting the same location data, so there's no benefit to copying it across from the cached 'past' record. Where the cached record had location data set manually by map or GridRef, then the location data should be copied across IF the record being edited does not have GPS based location data. However, this distinction might in itself be as confusing as the current behaviour.

Maybe the app functionality also needs updating so you can set and lock location name and location data independently to make things clear.
