### ISSUE TITLE
Activities: none are showing up in the app

### ISSUE THREAD

**Issue by charlesroper** [NERC-CEH/irecord-app#87]
I've got several activities available to me in the desktop web app, but these aren't showing up in the mobile app. I've tried fiddling with the closing times of a couple of activities to make double sure they're still considered "active", but no joy. I didn't leave it for very long and so it's possible the list of active activities are being cached by the app?

Desktop: ![2016-05-23_14h36_45](https://cloud.githubusercontent.com/assets/176/15472635/15f894c4-20f4-11e6-8bc6-cb4738283855.png)

App: ![screenshot_2016-05-23-14-39-29](https://cloud.githubusercontent.com/assets/176/15472744/9371fdf0-20f4-11e6-9fc6-4b46d9f233dc.png)

cc: @johnvanbreda

**Comment by johnvanbreda** [comment]
In order for an activity to appear, the "Edit an app record" page must be linked to the activity. This is a way for the activity admin to state that the activity will accept app records (otherwise we'll get app records being posted into an activity that has a very specific methodology which can't use the generic format provided by the current app). 
Agree this needs some instructions - I'll just check with Karolis if he started on them.

**Comment by charlesroper** [comment]
Great, yes, I can confirm that works.
