### ISSUE TITLE
Can organisations use the app?

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#93]
If an organisation is using a single account to input their records to iRecord, can several individuals use this same account to input their records via their mobile phones?

**Comment by kazlauskis** [comment]
Hi Graham, it is a good question. We prefer individuals to have their own account. iRecord has [organisational activities](http://www.brc.ac.uk/irecord/organisations/list) that might be what you are after?

BiologicalRecordsCentre/iRecord#63

**Comment by grahamcheckley** [comment]
Hi, what I needed to be able to do is group certain iRecord users for reporting and I can do that by creating an activity.  The issue with the activity and hence the app is that if I get more individuals with their own accounts is that while I can see the records and create reports from the activity I can't download them.  Will setting up an Organisation solve this download problem for me?

**Comment by kitenetter** [comment]
Graham, at the moment setting up an organisational activity will not enable you to download the records, but we are due to add this function in the near future. However, you will only be able to download records that have been explicitly added to the activity. So if you do set something up you should ensure that all your contributing recorders are aware of that, and do set things so that any relevant records that they add are linked to the activity. This can be done via the app, see http://www.brc.ac.uk/irecord/irecord-app-activity

**Comment by grahamcheckley** [comment]
Hi, we currently have 11k records input - what can be done with these?

**Comment by kitenetter** [comment]
Graham, could you send an email to irecord@ceh.ac.uk and I'll look into this.

**Comment by grahamcheckley** [comment]
email now with Martin.
