### ISSUE TITLE
Map view of records

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#97]
Provide more views (map, photo list etc) on user records.

![screen shot 2016-08-02 at 10 11 21](https://cloud.githubusercontent.com/assets/7383162/17323325/a9b2e016-5899-11e6-8cb3-d1231a8f7698.png)

**Comment by grahamcheckley** [comment]
I would suggest that any new app features prioritise improving the accuracy of the information captured by the app rather than adding features that resemble the main iRecord system.  For example having my pre-defined sites appearing as I start to type a location name would be a bit of a time saver and avoid simple spelling mistakes.

**Comment by kazlauskis** [comment]
Agree! This is just to log some of the better ideas.

**Comment by kazlauskis** [comment]
From a forum user:

> Might it be possible to make a couple of additions to the map view:
> 1) Toggle the visble records by 'this year', and 'all years'. This enables you to distinguish record ages.
> 2) Toggle by irecord 'speces group' to, for example, only display butterfly records
> 3) I think that currently only records submitted via the app are shown on the map. Could the app pull down / synch all irecord records so that browser submitted records and irecord butterfly app records are also shown. This would help merge the separate pools of data that exist currently.
